# fly.toml app configuration file generated for cold-rain-2283 on 2023-06-08T16:56:00-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "cold-rain-2283"
primary_region = "gru"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
