# fly.toml app configuration file generated for my-master-application on 2023-06-24T11:21:06-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "my-master-application"
primary_region = "gru"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
